<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../middleware/auth.php';
require_once __DIR__ . '/../../config/notifications.php';
header('Content-Type: application/json; charset=utf-8');
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); echo json_encode(['ok'=>false,'message'=>'Method Not Allowed'],JSON_UNESCAPED_UNICODE); exit; }
$user=require_role(['reviewer']);$data=json_decode(file_get_contents('php://input'),true) ?: $_POST;$articleId=(int)($data['article_id']??0);$score=(int)($data['score']??-1);$comment=trim((string)($data['comment']??''));$suggestion=strtolower(trim((string)($data['suggestion']??'')));
if($articleId<1||$score<0||$score>100||!in_array($suggestion,['accept','reject','revision'],true)){http_response_code(422);echo json_encode(['ok'=>false,'message'=>'اطلاعات داوری نامعتبر است.'],JSON_UNESCAPED_UNICODE);exit;}
$pdo=db();$stmt=$pdo->prepare('SELECT id FROM article_reviewers WHERE article_id=? AND reviewer_id=? LIMIT 1');$stmt->execute([$articleId,(int)$user['id']]);if(!$stmt->fetch()){http_response_code(403);echo json_encode(['ok'=>false,'message'=>'این مقاله به شما ارجاع نشده است.'],JSON_UNESCAPED_UNICODE);exit;}
$stmt=$pdo->prepare('SELECT id FROM reviews WHERE article_id=? AND reviewer_id=? LIMIT 1');$stmt->execute([$articleId,(int)$user['id']]);if($stmt->fetch()){http_response_code(409);echo json_encode(['ok'=>false,'message'=>'شما قبلاً این مقاله را داوری کرده‌اید.'],JSON_UNESCAPED_UNICODE);exit;}
try{$pdo->beginTransaction();$stmt=$pdo->prepare('INSERT INTO reviews(article_id,reviewer_id,score,comment,suggestion) VALUES(?,?,?,?,?)');$stmt->execute([$articleId,(int)$user['id'],$score,$comment?:null,$suggestion]);$stmt=$pdo->prepare('UPDATE article_reviewers SET status=\'completed\' WHERE article_id=? AND reviewer_id=?');$stmt->execute([$articleId,(int)$user['id']]);$statusMap=['accept'=>'accepted','reject'=>'rejected','revision'=>'revision'];$finalStatus=$statusMap[$suggestion];$pdo->prepare("UPDATE articles SET status=?, final_decision=? WHERE id=? AND final_decision IS NULL")->execute([$finalStatus,$suggestion,$articleId]);$articleInfoStmt=$pdo->prepare('SELECT title,author_id FROM articles WHERE id=? LIMIT 1');$articleInfoStmt->execute([$articleId]);$articleInfo=$articleInfoStmt->fetch();if($articleInfo){$outcome=['accept'=>'پذیرفته شد','reject'=>'رد شد','revision'=>'نیازمند اصلاح است'][$suggestion];notify_user($pdo,(int)$articleInfo['author_id'],'نتیجه داوری مقاله','مقاله «'.$articleInfo['title'].'» '.$outcome.' شد.','review');notify_roles($pdo,['secretariat','admin'],'نتیجه داوری ثبت شد','نتیجه داوری مقاله «'.$articleInfo['title'].'»: '.$outcome.'.','review');}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();http_response_code(500);echo json_encode(['ok'=>false,'message'=>'ثبت داوری انجام نشد.'],JSON_UNESCAPED_UNICODE);exit;}
echo json_encode(['ok'=>true,'message'=>'داوری با موفقیت ثبت شد.'],JSON_UNESCAPED_UNICODE);
